actions:
  create-dircolors: actions/create-dircolors.sh > {0}
config:
  longkey: false
  banner: true
  keepdot: false
  dotpath: dotfiles
  showdiff: false
  workdir: ~/.config/dotdrop
  backup: true
  cmpignore:
  - '*~'
  ignoreempty: false
  create: true
  link_on_import: nolink
  link_dotfile_default: nolink
  upignore:
  - '*~'
profiles:
  marvin:
    dotfiles:
    - f_zshenv
    - d_zsh
    - f_shrc
    - d_sh
    - f_init.el
    - f_ssh_config
  uz:
    dotfiles:
    - f_shrc
    - d_sh
    - f_init.el
    - f_ssh_config
dotfiles:
  d_sh:
    src: sh
    cmpignore:
    - dir_colors
    actions:
    - create-dircolors "~/.sh/dir_colors"
    dst: ~/.sh
    upignore:
    - dir_colors
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  d_zsh:
    src: zsh
    cmpignore:
    - '*/.zcompdump'
    - '*/histfile'
    - '*/zsh_plugins.sh'
    dst: ~/.zsh
    upignore:
    - '*/.zcompdump'
    - '*/histfile'
    - '*/zsh_plugins.sh'
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
  f_shrc:
    src: shrc
    dst: ~/.shrc
  f_init.el:
    src: emacs.d/init.el
    dst: ~/.emacs.d/init.el
