actions:
  sh-create-dircolors: actions/create-dircolors.sh > {0}
  ssh-create-control-dir: mkdir -p {{@@ ssh_control_path @@}}
  atom-install-packages: >-
    export PATH="$(which python2 | xargs dirname):$PATH";
    apm install --packages-file {0}
trans_write:
  atom-list-packages: apm list --installed --bare > {1}
variables:
  ssh_control_path: '~/.ssh/control'
config:
  longkey: false
  banner: true
  keepdot: false
  dotpath: dotfiles
  showdiff: false
  workdir: ~/.config/dotdrop
  backup: true
  cmpignore:
    - '*~'
  ignoreempty: false
  create: true
  link_on_import: nolink
  link_dotfile_default: nolink
  upignore:
    - '*~'
profiles:
  marvin:
    dotfiles:
      - f_zshenv
      - d_zsh
      - f_shrc
      - d_sh
      - f_init.el
      - f_ssh_config
      - f_gitconfig
    include:
      - atom
    variables:
      atom_user_id: "fdd86f3e-38a3-4c44-a218-73ff4584d223"
  uz:
    dotfiles:
      - f_shrc
      - d_sh
      - f_init.el
      - f_ssh_config
      - f_gitconfig
    include:
      - atom
    variables:
      atom_user_id: "36ea07cf-bb1d-4689-9c15-e24f14a5b7d0"
  atom:
    dotfiles:
      - f_atom_packages.list
      - f_atom_config.cson
      - f_atom_keymap.cson
dotfiles:
  d_sh:
    src: sh
    cmpignore:
      - dir_colors
    actions:
      - sh-create-dircolors "~/.sh/dir_colors"
    dst: ~/.sh
    upignore:
      - dir_colors
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  d_zsh:
    src: zsh
    cmpignore:
      - '*/.zcompdump'
      - '*/histfile'
      - '*/zsh_plugins.sh'
    dst: ~/.zsh
    upignore:
      - '*/.zcompdump'
      - '*/histfile'
      - '*/zsh_plugins.sh'
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
    actions:
      - ssh-create-control-dir
  f_shrc:
    src: shrc
    dst: ~/.shrc
  f_init.el:
    src: emacs.d/init.el
    dst: ~/.emacs.d/init.el
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_atom_packages.list:
    src: atom/packages.list
    dst: /tmp/atom-packages.list
    trans_write: atom-list-packages
    actions:
      - atom-install-packages '{{@@ _dotfile_abs_dst @@}}'
  f_atom_config.cson:
    src: atom/config.cson
    dst: ~/.atom/config.cson
  f_atom_keymap.cson:
    src: atom/keymap.cson
    dst: ~/.atom/keymap.cson
