actions:
  sh-create-dircolors: actions/create-dircolors.sh > {0}
  ssh-create-control-dir: mkdir -p {{@@ ssh_control_path @@}}
  atom-install-packages: >-
    export PATH="$(which python2 | xargs dirname):$PATH";
    apm install --packages-file {0}
  post:
    zsh-bundle-plugins: antibody bundle < {0}.txt > {0}.sh
trans_write:
  atom-list-packages: apm list --installed --bare > {1}
variables:
  ssh_control_path: ~/.ssh/control
config:
  backup: true
  banner: true
  cmpignore:
  - '*~'
  create: true
  dotpath: dotfiles
  ignoreempty: false
  import_variables:
  - secret-vars.yaml
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: true
  template_dotfile_default: false
  upignore:
  - '*~'
  workdir: ~/.config/dotdrop
profiles:
  marvin:
    include:
    - sh
    - zsh
    - bash
    - misc
    - openbox
    - vscode
    - av
    - gpg-agent
    dotfiles:
    - f_asoundrc
    - f_mimeapps.list
  uz:
    include:
    - atom
    - sh
    - zsh
    - bash
    - misc
    - openbox
    - av
    variables:
      atom_user_id: 36ea07cf-bb1d-4689-9c15-e24f14a5b7d0
  sh:
    dotfiles:
    - f_shrc
    - d_sh
  zsh:
    dotfiles:
    - f_zshenv
    - d_zsh
  bash:
    dotfiles:
    - f_bashrc
  misc:
    dotfiles:
    - f_emacs_init.el
    - d_emacs_elpa
    - f_ssh_config
    - f_gitconfig
    - d_byobu
    - d_xenv
  atom:
    dotfiles:
    - f_atom_packages.list
    - f_atom_config.cson
    - f_atom_keymap.cson
  openbox:
    dotfiles:
    - d_openbox
    - d_autorandr
    - d_tint2
    - f_xscreensaver
    - d_caffeine
    - d_volumeicon
    - d_autostart
  vscode:
    dotfiles:
    - f_vscode_settings.json
    - f_vscode_keybindings.json
    - d_vscode_snippets
  av:
    dotfiles:
    - f_mpsyt_config
    - d_mpv
  gpg-agent:
    dotfiles:
    - f_gpg-agent.conf
    - f_gpg_sshcontrol
dotfiles:
  d_sh:
    src: config/sh
    cmpignore:
    - dir_colors
    actions:
    - sh-create-dircolors "{{@@ _dotfile_abs_dst @@}}/dir_colors"
    dst: ~/.config/sh
    upignore:
    - dir_colors
    template: true
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  d_zsh:
    src: config/zsh
    cmpignore:
    - '*/.zcompdump'
    - '*/histfile'
    - '*/zsh_plugins_pre.sh'
    - '*/zsh_plugins_post.sh'
    dst: ~/.config/zsh
    upignore:
    - '*/.zcompdump'
    - '*/histfile'
    - '*/zsh_plugins_pre.sh'
    - '*/zsh_plugins_post.sh'
    actions:
    - zsh-bundle-plugins "{{@@ _dotfile_abs_dst @@}}/zsh_plugins_pre"
    - zsh-bundle-plugins "{{@@ _dotfile_abs_dst @@}}/zsh_plugins_post"
    template: true
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
    actions:
    - ssh-create-control-dir
    template: true
  f_shrc:
    src: shrc
    dst: ~/.shrc
  f_emacs_init.el:
    src: emacs.d/init.el
    dst: ~/.emacs.d/init.el
  d_emacs_elpa:
    src: emacs.d/elpa
    dst: ~/.emacs.d/elpa
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_atom_packages.list:
    src: atom/packages.list
    dst: ~/.atom/packages.list
    trans_write: atom-list-packages
    actions:
    - atom-install-packages '{{@@ _dotfile_abs_dst @@}}'
  f_atom_config.cson:
    src: atom/config.cson
    dst: ~/.atom/config.cson
    template: true
  f_atom_keymap.cson:
    src: atom/keymap.cson
    dst: ~/.atom/keymap.cson
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    template: true
  f_asoundrc:
    src: asoundrc
    dst: ~/.asoundrc
  d_tint2:
    src: config/tint2
    dst: ~/.config/tint2
  d_openbox:
    src: config/openbox
    dst: ~/.config/openbox
    cmpignore:
    - sfondi
    - lxqt-rc.xml
    upignore:
    - sfondi
    - lxqt-rc.xml
  d_byobu:
    src: config/byobu
    dst: ~/.config/byobu
    cmpignore:
    - '*/.ssh-agent'
    upignore:
    - '*/.ssh-agent'
  d_xenv:
    src: config/Xenv
    dst: ~/.config/Xenv
  f_xscreensaver:
    src: xscreensaver-{{@@ profile @@}}
    dst: ~/.xscreensaver
  f_mpsyt_config:
    src: config/mps-youtube/config.json
    dst: ~/.config/mps-youtube/config.json
    template: true
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
  d_caffeine:
    src: config/caffeine
    dst: ~/.config/caffeine
  f_vscode_settings.json:
    src: config/Code/User/settings.json
    dst: ~/.config/Code - OSS/User/settings.json
  f_vscode_keybindings.json:
    src: config/Code/User/keybindings.json
    dst: ~/.config/Code - OSS/User/keybindings.json
  d_vscode_snippets:
    src: config/Code/User/snippets
    dst: ~/.config/Code - OSS/User/snippets
  d_mpv:
    src: config/mpv
    dst: ~/.config/mpv
    chmod: '700'
  d_autorandr:
    src: config/autorandr
    dst: ~/.config/autorandr
  f_gpg-agent.conf:
    src: gnupg/gpg-agent.conf
    dst: ~/.gnupg/gpg-agent.conf
    chmod: '644'
  f_gpg_sshcontrol:
    src: gnupg/sshcontrol
    dst: ~/.gnupg/sshcontrol
    chmod: '644'
  d_volumeicon:
    src: config/volumeicon
    dst: ~/.config/volumeicon
  d_autostart:
    src: config/autostart
    dst: ~/.config/autostart
    chmod: '755'
