actions:
  sh-create-dircolors: actions/create-dircolors.sh > {0}
  ssh-create-control-dir: mkdir -p {{@@ ssh_control_path @@}}
  atom-install-packages: >-
    export PATH="$(which python2 | xargs dirname):$PATH";
    apm install --packages-file {0}
  post:
    zsh-bundle-plugins: antibody bundle < {0}.txt > {0}.sh
trans_write:
  atom-list-packages: apm list --installed --bare > {1}
variables:
  ssh_control_path: ~/.ssh/control
dynvariables:
  mpsyt_api_key: cat secrets/yt-apikey
config:
  longkey: false
  banner: true
  keepdot: false
  dotpath: dotfiles
  showdiff: false
  workdir: ~/.config/dotdrop
  backup: true
  cmpignore:
  - '*~'
  ignoreempty: false
  create: true
  link_on_import: nolink
  link_dotfile_default: nolink
  upignore:
  - '*~'
profiles:
  marvin:
    include:
    - atom
    - sh
    - zsh
    - bash
    - misc
    - openbox
    variables:
      atom_user_id: fdd86f3e-38a3-4c44-a218-73ff4584d223
    dotfiles:
    - f_asoundrc
  uz:
    include:
    - atom
    - sh
    - zsh
    - bash
    - misc
    - openbox
    # - xfce4
    variables:
      atom_user_id: 36ea07cf-bb1d-4689-9c15-e24f14a5b7d0
  sh:
    dotfiles:
    - f_shrc
    - d_sh
  zsh:
    dotfiles:
    - f_zshenv
    - d_zsh
  bash:
    dotfiles:
    - f_bashrc
  misc:
    dotfiles:
    - f_emacs_init.el
    - d_emacs_elpa
    - f_ssh_config
    - f_gitconfig
    - d_byobu
    - d_xenv
    - f_mpsyt_config
    - f_mimeapps.list
  atom:
    dotfiles:
    - f_atom_packages.list
    - f_atom_config.cson
    - f_atom_keymap.cson
  xfce4:
    dotfiles:
    - f_xfce4-helpers.rc
    - f_xfce4-screenshooter
    - f_xfce4-keyboard-shortcuts.xml
    - f_xfce4-power-manager.xml
    - d_xfce4-panel
    - f_xfce4-panel.xml
  openbox:
    dotfiles:
    - d_openbox
    - d_tint2
    - f_xscreensaver
dotfiles:
  d_sh:
    src: config/sh
    cmpignore:
    - dir_colors
    actions:
    - sh-create-dircolors "{{@@ _dotfile_abs_dst @@}}/dir_colors"
    dst: ~/.config/sh
    upignore:
    - dir_colors
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  d_zsh:
    src: config/zsh
    cmpignore:
    - '*/.zcompdump'
    - '*/histfile'
    - '*/zsh_plugins_pre.sh'
    - '*/zsh_plugins_post.sh'
    dst: ~/.config/zsh
    upignore:
    - '*/.zcompdump'
    - '*/histfile'
    - '*/zsh_plugins_pre.sh'
    - '*/zsh_plugins_post.sh'
    actions:
    - zsh-bundle-plugins "{{@@ _dotfile_abs_dst @@}}/zsh_plugins_pre"
    - zsh-bundle-plugins "{{@@ _dotfile_abs_dst @@}}/zsh_plugins_post"
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
    actions:
    - ssh-create-control-dir
  f_shrc:
    src: shrc
    dst: ~/.shrc
  f_emacs_init.el:
    src: emacs.d/init.el
    dst: ~/.emacs.d/init.el
  d_emacs_elpa:
    src: emacs.d/elpa
    dst: ~/.emacs.d/elpa
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_atom_packages.list:
    src: atom/packages.list
    dst: ~/.atom/packages.list
    trans_write: atom-list-packages
    actions:
    - atom-install-packages '{{@@ _dotfile_abs_dst @@}}'
  f_atom_config.cson:
    src: atom/config.cson
    dst: ~/.atom/config.cson
  f_atom_keymap.cson:
    src: atom/keymap.cson
    dst: ~/.atom/keymap.cson
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_xfce4-helpers.rc:
    src: config/xfce4/helpers.rc
    dst: ~/.config/xfce4/helpers.rc
  f_xfce4-screenshooter:
    src: config/xfce4/xfce4-screenshooter
    dst: ~/.config/xfce4/xfce4-screenshooter
  f_xfce4-keyboard-shortcuts.xml:
    src: config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
    dst: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
  f_xfce4-power-manager.xml:
    src: config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml
    dst: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml
  d_xfce4-panel:
    src: config/xfce4/panel
    dst: ~/.config/xfce4/panel
  f_xfce4-panel.xml:
    src: config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
    dst: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
  f_asoundrc:
    src: asoundrc
    dst: ~/.asoundrc
  d_tint2:
    src: config/tint2
    dst: ~/.config/tint2
  d_openbox:
    src: config/openbox
    dst: ~/.config/openbox
    cmpignore:
    - sfondi
    - lxqt-rc.xml
    upignore:
    - sfondi
    - lxqt-rc.xml
  d_byobu:
    src: config/byobu
    dst: ~/.config/byobu
    cmpignore:
    - '*/.ssh-agent'
    upignore:
    - '*/.ssh-agent'
  d_xenv:
    src: config/Xenv
    dst: ~/.config/Xenv
  f_xscreensaver:
    src: xscreensaver
    dst: ~/.xscreensaver
  f_mpsyt_config:
    src: config/mps-youtube/config.json
    dst: ~/.config/mps-youtube/config.json
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
