actions:
  sh-create-dircolors: actions/create-dircolors.sh > {0}
  makedir: mkdir -p {0}
  post:
    zsh-bundle-plugins: antibody bundle < {0}.txt > {0}.sh
variables:
  ssh_control_path: ~/.ssh/control
config:
  backup: true
  banner: true
  cmpignore:
  - '*~'
  create: true
  dotpath: dotfiles
  ignoreempty: false
  import_variables:
  - secret-vars.yaml
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: true
  template_dotfile_default: false
  upignore:
  - '*~'
  workdir: ~/.config/dotdrop
  minversion: 1.14.0
profiles:
  marvin:
    include:
    - sh
    - zsh
    - bash
    - misc
    - openbox
    - codeoss
    - av
    - gpg-agent
    dotfiles:
    - f_asoundrc
  zenithia:
    include:
    - sh
    - zsh
    - bash
    - misc
    - vscodium
    - av
    - gpg-agent
    - i3
  uz:
    include:
    - sh
    - zsh
    - bash
    - misc
    - openbox
    - av
  sh:
    dotfiles:
    - f_shrc
    - d_sh
  zsh:
    dotfiles:
    - f_zshenv
    - d_zsh
  bash:
    dotfiles:
    - f_bashrc
  misc:
    dotfiles:
    - f_emacs_init.el
    - d_emacs_elpa
    - f_ssh_config
    - f_gitconfig
    - d_byobu
    - f_mimeapps.list
  xgeneric:
    dotfiles:
    - d_xenv
    - f_xsessionrc
  openbox:
    dotfiles:
    - d_openbox
    - d_autorandr
    - d_tint2
    - f_xscreensaver
    - d_caffeine
    - f_xfce4-notifyd.xml
    - d_autostart
    - d_wallpapers
  i3:
    dotfiles:
    - d_i3
    - d_autorandr
    - d_tint2
    - f_xscreensaver
    - f_xfce4-notifyd.xml
    - d_systemd_user
    - d_wallpapers
    include:
    - xgeneric
    - gtk
  codeoss:
    dotfiles:
    - f_vscode_settings.json
    - f_vscode_keybindings.json
    - d_vscode_snippets
  vscodium:
    dotfiles:
    - f_codium_settings.json
    - f_codium_keybindings.json
    - d_codium_snippets
  av:
    dotfiles:
    - f_mpsyt_config
    - d_mpv
  gpg-agent:
    dotfiles:
    - f_gpg-agent.conf
    - f_gpg_sshcontrol
  gtk:
    dotfiles:
    - f_gtkrc-2.0
    - f_gtk3_settings.ini
dotfiles:
  d_sh:
    src: config/sh
    cmpignore:
    - dir_colors
    actions:
    - sh-create-dircolors "{{@@ _dotfile_abs_dst @@}}/dir_colors"
    dst: ~/.config/sh
    upignore:
    - dir_colors
    template: true
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  d_zsh:
    src: config/zsh
    cmpignore:
    - '*/.zcompdump'
    - '*/histfile'
    - '*/zsh_plugins_pre.sh'
    - '*/zsh_plugins_post.sh'
    dst: ~/.config/zsh
    upignore:
    - '*/.zcompdump'
    - '*/histfile'
    - '*/zsh_plugins_pre.sh'
    - '*/zsh_plugins_post.sh'
    actions:
    - zsh-bundle-plugins "{{@@ _dotfile_abs_dst @@}}/zsh_plugins_pre"
    - zsh-bundle-plugins "{{@@ _dotfile_abs_dst @@}}/zsh_plugins_post"
    template: true
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
    actions:
    - makedir "{{@@ ssh_control_path @@}}"
    template: true
  f_shrc:
    src: shrc
    dst: ~/.shrc
  f_emacs_init.el:
    src: emacs.d/init.el
    dst: ~/.emacs.d/init.el
  d_emacs_elpa:
    src: emacs.d/elpa
    dst: ~/.emacs.d/elpa
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    template: true
  f_asoundrc:
    src: asoundrc
    dst: ~/.asoundrc
  d_tint2:
    src: config/tint2
    dst: ~/.config/tint2
  d_openbox:
    src: config/openbox
    dst: ~/.config/openbox
    cmpignore:
    - wallpapers/*
    - lxqt-rc.xml
    upignore:
    - wallpapers/*
    - lxqt-rc.xml
  d_byobu:
    src: config/byobu
    dst: ~/.config/byobu
    cmpignore:
    - '*/.ssh-agent'
    upignore:
    - '*/.ssh-agent'
  d_xenv:
    src: config/Xenv
    dst: ~/.config/Xenv
  f_xscreensaver:
    src: xscreensaver-{{@@ profile @@}}
    dst: ~/.xscreensaver
  f_mpsyt_config:
    src: config/mps-youtube/config.json
    dst: ~/.config/mps-youtube/config.json
    template: true
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
    chmod: '600'
  d_caffeine:
    src: config/caffeine
    dst: ~/.config/caffeine
  f_vscode_settings.json:
    src: config/Code/User/settings.json
    dst: ~/.config/Code - OSS/User/settings.json
  f_vscode_keybindings.json:
    src: config/Code/User/keybindings.json
    dst: ~/.config/Code - OSS/User/keybindings.json
  d_vscode_snippets:
    src: config/Code/User/snippets
    dst: ~/.config/Code - OSS/User/snippets
  d_mpv:
    src: config/mpv
    dst: ~/.config/mpv
    cmpignore:
    - watch_later
    upignore:
    - watch_later
  d_autorandr:
    src: config/autorandr-{{@@ profile @@}}
    dst: ~/.config/autorandr
  f_gpg-agent.conf:
    src: gnupg/gpg-agent.conf
    dst: ~/.gnupg/gpg-agent.conf
    chmod: '644'
  f_gpg_sshcontrol:
    src: gnupg/sshcontrol
    dst: ~/.gnupg/sshcontrol
    chmod: '644'
  d_volumeicon:
    src: config/volumeicon
    dst: ~/.config/volumeicon
  d_autostart:
    src: config/autostart
    dst: ~/.config/autostart
    chmod: '755'
  f_xfce4-notifyd.xml:
    src: config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml
    dst: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml
  f_codium_settings.json:
    src: config/Code/User/settings.json
    dst: ~/.config/VSCodium/User/settings.json
  f_codium_keybindings.json:
    src: config/Code/User/keybindings.json
    dst: ~/.config/VSCodium/User/keybindings.json
  d_codium_snippets:
    src: config/Code/User/snippets
    dst: ~/.config/VSCodium/User/snippets
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  f_xsessionrc:
    src: xsessionrc
    dst: ~/.xsessionrc
  d_systemd_user:
    src: config/systemd/user
    dst: ~/.config/systemd/user
  f_gtkrc-2.0:
    src: gtkrc-2.0
    dst: ~/.gtkrc-2.0
  f_gtk3_settings.ini:
    src: config/gtk-3.0/settings.ini
    dst: ~/.config/gtk-3.0/settings.ini
  d_wallpapers:
    src: config/wallpapers
    dst: ~/.config/wallpapers
    cmpignore:
    - images
    upignore:
    - images
    actions:
    - makedir "~/.config/wallpapers/images"
